version: '3.8'

services:
    app:
        build: ./
        command: streamlit run app/streamlit_app.py --server.port 8501
        volumes:
            - .:/
        ports:
            - 8501:8501
        image: reflect-docker:latest
