# .circleci/config.yml
defaults: &defaults
  docker:
    - image: python:3.8
  working_directory: ~/project
  environment:
    BASH_ENV: "~/.bashrc"
 
version: 2.1
jobs:
    build:
      <<: *defaults
      steps:
        - checkout  # checkout source code to working directory
        - run:
            command: |
              python -m venv /root/.env
              source /root/.env/bin/activate
              python -m pip install pytest pytest-cov
              python setup.py install
        - save_cache:
             key: "deps_4"
             paths: 
                - /root/.env/lib/python3.8/site-packages
                - /root/.env
    check_install:          
      <<: *defaults
      steps:
        - checkout  # checkout source code to working directory
        - restore_cache:
             keys:
               - "deps_4"
        - run:
            name: start app
            command: |
               source /root/.env/bin/activate
               ps
               ./app.sh       
        - run:
            name: stop app
            command: |
               kill $(ps aux | grep "[p]ython" | awk '{print $2}')
    test:          
      <<: *defaults
      steps:
        - checkout  # checkout source code to working directory
        - restore_cache:
             keys:
               - "install_dep"
        - run:
            command: |
              source /root/.env/bin/activate
              pytest .                       
workflows:
  integration:
    jobs:
      - build
      - check_install:
          requires:
              - build 
